/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.home.jooq.tables.Scanresult;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScanresultRecord extends UpdatableRecordImpl<ScanresultRecord> implements Record17<BigDecimal, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

	private static final long serialVersionUID = 1503863525;

	/**
	 * Setter for <code>ScanResult.scan_id</code>.
	 */
	public void setScanId(BigDecimal value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ScanResult.scan_id</code>.
	 */
	public BigDecimal getScanId() {
		return (BigDecimal) getValue(0);
	}

	/**
	 * Setter for <code>ScanResult.scan_time</code>.
	 */
	public void setScanTime(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ScanResult.scan_time</code>.
	 */
	public String getScanTime() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ScanResult.parse_time</code>.
	 */
	public void setParseTime(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ScanResult.parse_time</code>.
	 */
	public String getParseTime() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ScanResult.glob_time</code>.
	 */
	public void setGlobTime(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ScanResult.glob_time</code>.
	 */
	public String getGlobTime() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ScanResult.pdf_books_count</code>.
	 */
	public void setPdfBooksCount(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ScanResult.pdf_books_count</code>.
	 */
	public Integer getPdfBooksCount() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>ScanResult.fb2_books_count</code>.
	 */
	public void setFb2BooksCount(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ScanResult.fb2_books_count</code>.
	 */
	public Integer getFb2BooksCount() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>ScanResult.epub_books_count</code>.
	 */
	public void setEpubBooksCount(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ScanResult.epub_books_count</code>.
	 */
	public Integer getEpubBooksCount() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>ScanResult.djvu_books_count</code>.
	 */
	public void setDjvuBooksCount(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ScanResult.djvu_books_count</code>.
	 */
	public Integer getDjvuBooksCount() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>ScanResult.txt_books_count</code>.
	 */
	public void setTxtBooksCount(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ScanResult.txt_books_count</code>.
	 */
	public Integer getTxtBooksCount() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>ScanResult.doc_books_count</code>.
	 */
	public void setDocBooksCount(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ScanResult.doc_books_count</code>.
	 */
	public Integer getDocBooksCount() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>ScanResult.cbr_books_count</code>.
	 */
	public void setCbrBooksCount(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ScanResult.cbr_books_count</code>.
	 */
	public Integer getCbrBooksCount() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>ScanResult.book_found_count</code>.
	 */
	public void setBookFoundCount(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ScanResult.book_found_count</code>.
	 */
	public Integer getBookFoundCount() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>ScanResult.empty_book_count</code>.
	 */
	public void setEmptyBookCount(Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ScanResult.empty_book_count</code>.
	 */
	public Integer getEmptyBookCount() {
		return (Integer) getValue(12);
	}

	/**
	 * Setter for <code>ScanResult.undefined_book_count</code>.
	 */
	public void setUndefinedBookCount(Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ScanResult.undefined_book_count</code>.
	 */
	public Integer getUndefinedBookCount() {
		return (Integer) getValue(13);
	}

	/**
	 * Setter for <code>ScanResult.scanned_path_count</code>.
	 */
	public void setScannedPathCount(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ScanResult.scanned_path_count</code>.
	 */
	public Integer getScannedPathCount() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>ScanResult.bad_files_count</code>.
	 */
	public void setBadFilesCount(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ScanResult.bad_files_count</code>.
	 */
	public Integer getBadFilesCount() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>ScanResult.ignored_path_count</code>.
	 */
	public void setIgnoredPathCount(Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ScanResult.ignored_path_count</code>.
	 */
	public Integer getIgnoredPathCount() {
		return (Integer) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<BigDecimal> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<BigDecimal, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
		return (Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<BigDecimal, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
		return (Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field1() {
		return Scanresult.SCANRESULT.SCAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Scanresult.SCANRESULT.SCAN_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Scanresult.SCANRESULT.PARSE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Scanresult.SCANRESULT.GLOB_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Scanresult.SCANRESULT.PDF_BOOKS_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Scanresult.SCANRESULT.FB2_BOOKS_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Scanresult.SCANRESULT.EPUB_BOOKS_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Scanresult.SCANRESULT.DJVU_BOOKS_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return Scanresult.SCANRESULT.TXT_BOOKS_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field10() {
		return Scanresult.SCANRESULT.DOC_BOOKS_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field11() {
		return Scanresult.SCANRESULT.CBR_BOOKS_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return Scanresult.SCANRESULT.BOOK_FOUND_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field13() {
		return Scanresult.SCANRESULT.EMPTY_BOOK_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field14() {
		return Scanresult.SCANRESULT.UNDEFINED_BOOK_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field15() {
		return Scanresult.SCANRESULT.SCANNED_PATH_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field16() {
		return Scanresult.SCANRESULT.BAD_FILES_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field17() {
		return Scanresult.SCANRESULT.IGNORED_PATH_COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value1() {
		return getScanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getScanTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getParseTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getGlobTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getPdfBooksCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getFb2BooksCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getEpubBooksCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getDjvuBooksCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getTxtBooksCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value10() {
		return getDocBooksCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value11() {
		return getCbrBooksCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getBookFoundCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value13() {
		return getEmptyBookCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value14() {
		return getUndefinedBookCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value15() {
		return getScannedPathCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value16() {
		return getBadFilesCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value17() {
		return getIgnoredPathCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value1(BigDecimal value) {
		setScanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value2(String value) {
		setScanTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value3(String value) {
		setParseTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value4(String value) {
		setGlobTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value5(Integer value) {
		setPdfBooksCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value6(Integer value) {
		setFb2BooksCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value7(Integer value) {
		setEpubBooksCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value8(Integer value) {
		setDjvuBooksCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value9(Integer value) {
		setTxtBooksCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value10(Integer value) {
		setDocBooksCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value11(Integer value) {
		setCbrBooksCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value12(Integer value) {
		setBookFoundCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value13(Integer value) {
		setEmptyBookCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value14(Integer value) {
		setUndefinedBookCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value15(Integer value) {
		setScannedPathCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value16(Integer value) {
		setBadFilesCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord value17(Integer value) {
		setIgnoredPathCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanresultRecord values(BigDecimal value1, String value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, Integer value16, Integer value17) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ScanresultRecord
	 */
	public ScanresultRecord() {
		super(Scanresult.SCANRESULT);
	}

	/**
	 * Create a detached, initialised ScanresultRecord
	 */
	public ScanresultRecord(BigDecimal scanId, String scanTime, String parseTime, String globTime, Integer pdfBooksCount, Integer fb2BooksCount, Integer epubBooksCount, Integer djvuBooksCount, Integer txtBooksCount, Integer docBooksCount, Integer cbrBooksCount, Integer bookFoundCount, Integer emptyBookCount, Integer undefinedBookCount, Integer scannedPathCount, Integer badFilesCount, Integer ignoredPathCount) {
		super(Scanresult.SCANRESULT);

		setValue(0, scanId);
		setValue(1, scanTime);
		setValue(2, parseTime);
		setValue(3, globTime);
		setValue(4, pdfBooksCount);
		setValue(5, fb2BooksCount);
		setValue(6, epubBooksCount);
		setValue(7, djvuBooksCount);
		setValue(8, txtBooksCount);
		setValue(9, docBooksCount);
		setValue(10, cbrBooksCount);
		setValue(11, bookFoundCount);
		setValue(12, emptyBookCount);
		setValue(13, undefinedBookCount);
		setValue(14, scannedPathCount);
		setValue(15, badFilesCount);
		setValue(16, ignoredPathCount);
	}
}
