/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables.records;


import javax.annotation.Generated;

import org.home.jooq.tables.ScanScannedPathList;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScanScannedPathListRecord extends TableRecordImpl<ScanScannedPathListRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = 477753460;

	/**
	 * Setter for <code>Scan_Scanned_path_list.scan_id</code>.
	 */
	public void setScanId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Scan_Scanned_path_list.scan_id</code>.
	 */
	public Integer getScanId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>Scan_Scanned_path_list.file_path_id</code>.
	 */
	public void setFilePathId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Scan_Scanned_path_list.file_path_id</code>.
	 */
	public String getFilePathId() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return ScanScannedPathList.SCAN_SCANNED_PATH_LIST.SCAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ScanScannedPathList.SCAN_SCANNED_PATH_LIST.FILE_PATH_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getScanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getFilePathId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanScannedPathListRecord value1(Integer value) {
		setScanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanScannedPathListRecord value2(String value) {
		setFilePathId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanScannedPathListRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ScanScannedPathListRecord
	 */
	public ScanScannedPathListRecord() {
		super(ScanScannedPathList.SCAN_SCANNED_PATH_LIST);
	}

	/**
	 * Create a detached, initialised ScanScannedPathListRecord
	 */
	public ScanScannedPathListRecord(Integer scanId, String filePathId) {
		super(ScanScannedPathList.SCAN_SCANNED_PATH_LIST);

		setValue(0, scanId);
		setValue(1, filePathId);
	}
}
