/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.home.jooq.tables.SessionScan;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionScanRecord extends TableRecordImpl<SessionScanRecord> implements Record2<String, BigDecimal> {

	private static final long serialVersionUID = 2015906600;

	/**
	 * Setter for <code>Session_scan.session_name</code>.
	 */
	public void setSessionName(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Session_scan.session_name</code>.
	 */
	public String getSessionName() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>Session_scan.scan_id</code>.
	 */
	public void setScanId(BigDecimal value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Session_scan.scan_id</code>.
	 */
	public BigDecimal getScanId() {
		return (BigDecimal) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, BigDecimal> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, BigDecimal> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return SessionScan.SESSION_SCAN.SESSION_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field2() {
		return SessionScan.SESSION_SCAN.SCAN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getSessionName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value2() {
		return getScanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionScanRecord value1(String value) {
		setSessionName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionScanRecord value2(BigDecimal value) {
		setScanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionScanRecord values(String value1, BigDecimal value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SessionScanRecord
	 */
	public SessionScanRecord() {
		super(SessionScan.SESSION_SCAN);
	}

	/**
	 * Create a detached, initialised SessionScanRecord
	 */
	public SessionScanRecord(String sessionName, BigDecimal scanId) {
		super(SessionScan.SESSION_SCAN);

		setValue(0, sessionName);
		setValue(1, scanId);
	}
}
