/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables.records;


import javax.annotation.Generated;

import org.home.jooq.tables.Session;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionRecord extends UpdatableRecordImpl<SessionRecord> implements Record9<Integer, String, Integer, String, String, String, String, String, String> {

	private static final long serialVersionUID = -2108579415;

	/**
	 * Setter for <code>Session.record_id</code>.
	 */
	public void setRecordId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Session.record_id</code>.
	 */
	public Integer getRecordId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>Session.session_name</code>.
	 */
	public void setSessionName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Session.session_name</code>.
	 */
	public String getSessionName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>Session.id</code>.
	 */
	public void setId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Session.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>Session.home_dir</code>.
	 */
	public void setHomeDir(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Session.home_dir</code>.
	 */
	public String getHomeDir() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>Session.user_name</code>.
	 */
	public void setUserName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Session.user_name</code>.
	 */
	public String getUserName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>Session.os_name</code>.
	 */
	public void setOsName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Session.os_name</code>.
	 */
	public String getOsName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>Session.os_version</code>.
	 */
	public void setOsVersion(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Session.os_version</code>.
	 */
	public String getOsVersion() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>Session.os_arch</code>.
	 */
	public void setOsArch(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>Session.os_arch</code>.
	 */
	public String getOsArch() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>Session.temp_directory</code>.
	 */
	public void setTempDirectory(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>Session.temp_directory</code>.
	 */
	public String getTempDirectory() {
		return (String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, Integer, String, String, String, String, String, String> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Integer, String, Integer, String, String, String, String, String, String> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Session.SESSION.RECORD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Session.SESSION.SESSION_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Session.SESSION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Session.SESSION.HOME_DIR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Session.SESSION.USER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Session.SESSION.OS_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Session.SESSION.OS_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Session.SESSION.OS_ARCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Session.SESSION.TEMP_DIRECTORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRecordId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSessionName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getHomeDir();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getUserName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getOsName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getOsVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getOsArch();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getTempDirectory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value1(Integer value) {
		setRecordId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value2(String value) {
		setSessionName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value3(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value4(String value) {
		setHomeDir(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value5(String value) {
		setUserName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value6(String value) {
		setOsName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value7(String value) {
		setOsVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value8(String value) {
		setOsArch(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord value9(String value) {
		setTempDirectory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SessionRecord
	 */
	public SessionRecord() {
		super(Session.SESSION);
	}

	/**
	 * Create a detached, initialised SessionRecord
	 */
	public SessionRecord(Integer recordId, String sessionName, Integer id, String homeDir, String userName, String osName, String osVersion, String osArch, String tempDirectory) {
		super(Session.SESSION);

		setValue(0, recordId);
		setValue(1, sessionName);
		setValue(2, id);
		setValue(3, homeDir);
		setValue(4, userName);
		setValue(5, osName);
		setValue(6, osVersion);
		setValue(7, osArch);
		setValue(8, tempDirectory);
	}
}
