/**
 * This class is generated by jOOQ
 */
package org.home.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.tables.BadFilesPathList;
import org.home.jooq.tables.Book;
import org.home.jooq.tables.EmptyBook;
import org.home.jooq.tables.IgnoredPathList;
import org.home.jooq.tables.ScanBadFilesPathList;
import org.home.jooq.tables.ScanBook;
import org.home.jooq.tables.ScanEmptyBook;
import org.home.jooq.tables.ScanScannedPathList;
import org.home.jooq.tables.ScanUndefinedBook;
import org.home.jooq.tables.ScanUndefinedPathList;
import org.home.jooq.tables.ScannedPathList;
import org.home.jooq.tables.Scanresult;
import org.home.jooq.tables.Session;
import org.home.jooq.tables.SessionScan;
import org.home.jooq.tables.SqliteSequence;
import org.home.jooq.tables.UndefinedBook;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = -1057047797;

	/**
	 * The reference instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			BadFilesPathList.BAD_FILES_PATH_LIST,
			Book.BOOK,
			EmptyBook.EMPTY_BOOK,
			Scanresult.SCANRESULT,
			ScanBadFilesPathList.SCAN_BAD_FILES_PATH_LIST,
			ScanBook.SCAN_BOOK,
			ScanEmptyBook.SCAN_EMPTY_BOOK,
			ScanScannedPathList.SCAN_SCANNED_PATH_LIST,
			ScanUndefinedBook.SCAN_UNDEFINED_BOOK,
			ScanUndefinedPathList.SCAN_UNDEFINED_PATH_LIST,
			ScannedPathList.SCANNED_PATH_LIST,
			Session.SESSION,
			SessionScan.SESSION_SCAN,
			UndefinedBook.UNDEFINED_BOOK,
			IgnoredPathList.IGNORED_PATH_LIST,
			SqliteSequence.SQLITE_SEQUENCE);
	}
}
