/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.BadFilesPathListRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BadFilesPathList extends TableImpl<BadFilesPathListRecord> {

	private static final long serialVersionUID = -1432339518;

	/**
	 * The reference instance of <code>Bad_files_path_list</code>
	 */
	public static final BadFilesPathList BAD_FILES_PATH_LIST = new BadFilesPathList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BadFilesPathListRecord> getRecordType() {
		return BadFilesPathListRecord.class;
	}

	/**
	 * The column <code>Bad_files_path_list.id</code>.
	 */
	public final TableField<BadFilesPathListRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Bad_files_path_list.file_path</code>.
	 */
	public final TableField<BadFilesPathListRecord, String> FILE_PATH = createField("file_path", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Bad_files_path_list</code> table reference
	 */
	public BadFilesPathList() {
		this("Bad_files_path_list", null);
	}

	/**
	 * Create an aliased <code>Bad_files_path_list</code> table reference
	 */
	public BadFilesPathList(String alias) {
		this(alias, BAD_FILES_PATH_LIST);
	}

	private BadFilesPathList(String alias, Table<BadFilesPathListRecord> aliased) {
		this(alias, aliased, null);
	}

	private BadFilesPathList(String alias, Table<BadFilesPathListRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<BadFilesPathListRecord> getPrimaryKey() {
		return Keys.PK_BAD_FILES_PATH_LIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<BadFilesPathListRecord>> getKeys() {
		return Arrays.<UniqueKey<BadFilesPathListRecord>>asList(Keys.PK_BAD_FILES_PATH_LIST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BadFilesPathList as(String alias) {
		return new BadFilesPathList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public BadFilesPathList rename(String name) {
		return new BadFilesPathList(name, null);
	}
}
