/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.EmptyBookRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmptyBook extends TableImpl<EmptyBookRecord> {

	private static final long serialVersionUID = 76636740;

	/**
	 * The reference instance of <code>Empty_book</code>
	 */
	public static final EmptyBook EMPTY_BOOK = new EmptyBook();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmptyBookRecord> getRecordType() {
		return EmptyBookRecord.class;
	}

	/**
	 * The column <code>Empty_book.scan_id</code>.
	 */
	public final TableField<EmptyBookRecord, String> SCAN_ID = createField("scan_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>Empty_book.id</code>.
	 */
	public final TableField<EmptyBookRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Empty_book.file_name</code>.
	 */
	public final TableField<EmptyBookRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.location_path</code>.
	 */
	public final TableField<EmptyBookRecord, String> LOCATION_PATH = createField("location_path", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.ext</code>.
	 */
	public final TableField<EmptyBookRecord, String> EXT = createField("ext", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.file_size</code>.
	 */
	public final TableField<EmptyBookRecord, String> FILE_SIZE = createField("file_size", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.title</code>.
	 */
	public final TableField<EmptyBookRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.author</code>.
	 */
	public final TableField<EmptyBookRecord, String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.number_of_pages</code>.
	 */
	public final TableField<EmptyBookRecord, Integer> NUMBER_OF_PAGES = createField("number_of_pages", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Empty_book.subject</code>.
	 */
	public final TableField<EmptyBookRecord, String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.description</code>.
	 */
	public final TableField<EmptyBookRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.creation_date</code>.
	 */
	public final TableField<EmptyBookRecord, String> CREATION_DATE = createField("creation_date", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.modification_date</code>.
	 */
	public final TableField<EmptyBookRecord, String> MODIFICATION_DATE = createField("modification_date", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.creator</code>.
	 */
	public final TableField<EmptyBookRecord, String> CREATOR = createField("creator", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.producer</code>.
	 */
	public final TableField<EmptyBookRecord, String> PRODUCER = createField("producer", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.keywords</code>.
	 */
	public final TableField<EmptyBookRecord, String> KEYWORDS = createField("keywords", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.lang</code>.
	 */
	public final TableField<EmptyBookRecord, String> LANG = createField("lang", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.version</code>.
	 */
	public final TableField<EmptyBookRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.have_cover</code>.
	 */
	public final TableField<EmptyBookRecord, Object> HAVE_COVER = createField("have_cover", org.jooq.impl.DefaultDataType.getDefaultDataType("BOOL"), this, "");

	/**
	 * The column <code>Empty_book.preview_image_file</code>.
	 */
	public final TableField<EmptyBookRecord, String> PREVIEW_IMAGE_FILE = createField("preview_image_file", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.isbn</code>.
	 */
	public final TableField<EmptyBookRecord, String> ISBN = createField("isbn", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.publisher_name</code>.
	 */
	public final TableField<EmptyBookRecord, String> PUBLISHER_NAME = createField("publisher_name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.publisher_book_name</code>.
	 */
	public final TableField<EmptyBookRecord, String> PUBLISHER_BOOK_NAME = createField("publisher_book_name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.publisher_city</code>.
	 */
	public final TableField<EmptyBookRecord, String> PUBLISHER_CITY = createField("publisher_city", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.publish_year</code>.
	 */
	public final TableField<EmptyBookRecord, String> PUBLISH_YEAR = createField("publish_year", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.is_deleted</code>.
	 */
	public final TableField<EmptyBookRecord, Object> IS_DELETED = createField("is_deleted", org.jooq.impl.DefaultDataType.getDefaultDataType("BOOL"), this, "");

	/**
	 * The column <code>Empty_book.encoding</code>.
	 */
	public final TableField<EmptyBookRecord, String> ENCODING = createField("encoding", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.annotaion</code>.
	 */
	public final TableField<EmptyBookRecord, String> ANNOTAION = createField("annotaion", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.genre</code>.
	 */
	public final TableField<EmptyBookRecord, String> GENRE = createField("genre", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.translator</code>.
	 */
	public final TableField<EmptyBookRecord, String> TRANSLATOR = createField("translator", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.src_lang</code>.
	 */
	public final TableField<EmptyBookRecord, String> SRC_LANG = createField("src_lang", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.src_genre</code>.
	 */
	public final TableField<EmptyBookRecord, String> SRC_GENRE = createField("src_genre", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.src_author</code>.
	 */
	public final TableField<EmptyBookRecord, String> SRC_AUTHOR = createField("src_author", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.src_title</code>.
	 */
	public final TableField<EmptyBookRecord, String> SRC_TITLE = createField("src_title", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.src_annotation</code>.
	 */
	public final TableField<EmptyBookRecord, String> SRC_ANNOTATION = createField("src_annotation", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.src_keywords</code>.
	 */
	public final TableField<EmptyBookRecord, String> SRC_KEYWORDS = createField("src_keywords", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Empty_book.src_date</code>.
	 */
	public final TableField<EmptyBookRecord, String> SRC_DATE = createField("src_date", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Empty_book</code> table reference
	 */
	public EmptyBook() {
		this("Empty_book", null);
	}

	/**
	 * Create an aliased <code>Empty_book</code> table reference
	 */
	public EmptyBook(String alias) {
		this(alias, EMPTY_BOOK);
	}

	private EmptyBook(String alias, Table<EmptyBookRecord> aliased) {
		this(alias, aliased, null);
	}

	private EmptyBook(String alias, Table<EmptyBookRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EmptyBookRecord> getPrimaryKey() {
		return Keys.PK_EMPTY_BOOK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EmptyBookRecord>> getKeys() {
		return Arrays.<UniqueKey<EmptyBookRecord>>asList(Keys.PK_EMPTY_BOOK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmptyBook as(String alias) {
		return new EmptyBook(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EmptyBook rename(String name) {
		return new EmptyBook(name, null);
	}
}
