/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.ScanUndefinedPathListRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScanUndefinedPathList extends TableImpl<ScanUndefinedPathListRecord> {

	private static final long serialVersionUID = -677434106;

	/**
	 * The reference instance of <code>Scan_Undefined_path_list</code>
	 */
	public static final ScanUndefinedPathList SCAN_UNDEFINED_PATH_LIST = new ScanUndefinedPathList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScanUndefinedPathListRecord> getRecordType() {
		return ScanUndefinedPathListRecord.class;
	}

	/**
	 * The column <code>Scan_Undefined_path_list.scan_id</code>.
	 */
	public final TableField<ScanUndefinedPathListRecord, Integer> SCAN_ID = createField("scan_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Scan_Undefined_path_list.file_path_id</code>.
	 */
	public final TableField<ScanUndefinedPathListRecord, String> FILE_PATH_ID = createField("file_path_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Scan_Undefined_path_list</code> table reference
	 */
	public ScanUndefinedPathList() {
		this("Scan_Undefined_path_list", null);
	}

	/**
	 * Create an aliased <code>Scan_Undefined_path_list</code> table reference
	 */
	public ScanUndefinedPathList(String alias) {
		this(alias, SCAN_UNDEFINED_PATH_LIST);
	}

	private ScanUndefinedPathList(String alias, Table<ScanUndefinedPathListRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScanUndefinedPathList(String alias, Table<ScanUndefinedPathListRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ScanUndefinedPathListRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ScanUndefinedPathListRecord, ?>>asList(Keys.FK_SCAN_UNDEFINED_PATH_LIST_SCANRESULT_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanUndefinedPathList as(String alias) {
		return new ScanUndefinedPathList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ScanUndefinedPathList rename(String name) {
		return new ScanUndefinedPathList(name, null);
	}
}
