/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.ScanUndefinedBookRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScanUndefinedBook extends TableImpl<ScanUndefinedBookRecord> {

	private static final long serialVersionUID = -1585348789;

	/**
	 * The reference instance of <code>Scan_Undefined_Book</code>
	 */
	public static final ScanUndefinedBook SCAN_UNDEFINED_BOOK = new ScanUndefinedBook();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScanUndefinedBookRecord> getRecordType() {
		return ScanUndefinedBookRecord.class;
	}

	/**
	 * The column <code>Scan_Undefined_Book.scan_id</code>.
	 */
	public final TableField<ScanUndefinedBookRecord, Integer> SCAN_ID = createField("scan_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Scan_Undefined_Book.book_scan_id</code>.
	 */
	public final TableField<ScanUndefinedBookRecord, String> BOOK_SCAN_ID = createField("book_scan_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Scan_Undefined_Book</code> table reference
	 */
	public ScanUndefinedBook() {
		this("Scan_Undefined_Book", null);
	}

	/**
	 * Create an aliased <code>Scan_Undefined_Book</code> table reference
	 */
	public ScanUndefinedBook(String alias) {
		this(alias, SCAN_UNDEFINED_BOOK);
	}

	private ScanUndefinedBook(String alias, Table<ScanUndefinedBookRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScanUndefinedBook(String alias, Table<ScanUndefinedBookRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ScanUndefinedBookRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ScanUndefinedBookRecord, ?>>asList(Keys.FK_SCAN_UNDEFINED_BOOK_SCANRESULT_1, Keys.FK_SCAN_UNDEFINED_BOOK_UNDEFINED_BOOK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanUndefinedBook as(String alias) {
		return new ScanUndefinedBook(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ScanUndefinedBook rename(String name) {
		return new ScanUndefinedBook(name, null);
	}
}
