/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.ScanEmptyBookRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScanEmptyBook extends TableImpl<ScanEmptyBookRecord> {

	private static final long serialVersionUID = -1439994260;

	/**
	 * The reference instance of <code>Scan_Empty_Book</code>
	 */
	public static final ScanEmptyBook SCAN_EMPTY_BOOK = new ScanEmptyBook();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScanEmptyBookRecord> getRecordType() {
		return ScanEmptyBookRecord.class;
	}

	/**
	 * The column <code>Scan_Empty_Book.scan_id</code>.
	 */
	public final TableField<ScanEmptyBookRecord, BigDecimal> SCAN_ID = createField("scan_id", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>Scan_Empty_Book.book_scan_id</code>.
	 */
	public final TableField<ScanEmptyBookRecord, String> BOOK_SCAN_ID = createField("book_scan_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Scan_Empty_Book</code> table reference
	 */
	public ScanEmptyBook() {
		this("Scan_Empty_Book", null);
	}

	/**
	 * Create an aliased <code>Scan_Empty_Book</code> table reference
	 */
	public ScanEmptyBook(String alias) {
		this(alias, SCAN_EMPTY_BOOK);
	}

	private ScanEmptyBook(String alias, Table<ScanEmptyBookRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScanEmptyBook(String alias, Table<ScanEmptyBookRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ScanEmptyBookRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ScanEmptyBookRecord, ?>>asList(Keys.FK_SCAN_EMPTY_BOOK_SCANRESULT_1, Keys.FK_SCAN_EMPTY_BOOK_EMPTY_BOOK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanEmptyBook as(String alias) {
		return new ScanEmptyBook(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ScanEmptyBook rename(String name) {
		return new ScanEmptyBook(name, null);
	}
}
