/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.ScanBadFilesPathListRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScanBadFilesPathList extends TableImpl<ScanBadFilesPathListRecord> {

	private static final long serialVersionUID = -1927614591;

	/**
	 * The reference instance of <code>Scan_Bad_files_path_list</code>
	 */
	public static final ScanBadFilesPathList SCAN_BAD_FILES_PATH_LIST = new ScanBadFilesPathList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScanBadFilesPathListRecord> getRecordType() {
		return ScanBadFilesPathListRecord.class;
	}

	/**
	 * The column <code>Scan_Bad_files_path_list.scan_id</code>.
	 */
	public final TableField<ScanBadFilesPathListRecord, BigDecimal> SCAN_ID = createField("scan_id", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>Scan_Bad_files_path_list.file_path_id</code>.
	 */
	public final TableField<ScanBadFilesPathListRecord, String> FILE_PATH_ID = createField("file_path_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Scan_Bad_files_path_list</code> table reference
	 */
	public ScanBadFilesPathList() {
		this("Scan_Bad_files_path_list", null);
	}

	/**
	 * Create an aliased <code>Scan_Bad_files_path_list</code> table reference
	 */
	public ScanBadFilesPathList(String alias) {
		this(alias, SCAN_BAD_FILES_PATH_LIST);
	}

	private ScanBadFilesPathList(String alias, Table<ScanBadFilesPathListRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScanBadFilesPathList(String alias, Table<ScanBadFilesPathListRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ScanBadFilesPathListRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ScanBadFilesPathListRecord, ?>>asList(Keys.FK_SCAN_BAD_FILES_PATH_LIST_SCANRESULT_1, Keys.FK_SCAN_BAD_FILES_PATH_LIST_BAD_FILES_PATH_LIST_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanBadFilesPathList as(String alias) {
		return new ScanBadFilesPathList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ScanBadFilesPathList rename(String name) {
		return new ScanBadFilesPathList(name, null);
	}
}
