/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.ScanScannedPathListRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScanScannedPathList extends TableImpl<ScanScannedPathListRecord> {

	private static final long serialVersionUID = 1416192094;

	/**
	 * The reference instance of <code>Scan_Scanned_path_list</code>
	 */
	public static final ScanScannedPathList SCAN_SCANNED_PATH_LIST = new ScanScannedPathList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScanScannedPathListRecord> getRecordType() {
		return ScanScannedPathListRecord.class;
	}

	/**
	 * The column <code>Scan_Scanned_path_list.scan_id</code>.
	 */
	public final TableField<ScanScannedPathListRecord, BigDecimal> SCAN_ID = createField("scan_id", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>Scan_Scanned_path_list.file_path_id</code>.
	 */
	public final TableField<ScanScannedPathListRecord, String> FILE_PATH_ID = createField("file_path_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Scan_Scanned_path_list</code> table reference
	 */
	public ScanScannedPathList() {
		this("Scan_Scanned_path_list", null);
	}

	/**
	 * Create an aliased <code>Scan_Scanned_path_list</code> table reference
	 */
	public ScanScannedPathList(String alias) {
		this(alias, SCAN_SCANNED_PATH_LIST);
	}

	private ScanScannedPathList(String alias, Table<ScanScannedPathListRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScanScannedPathList(String alias, Table<ScanScannedPathListRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ScanScannedPathListRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ScanScannedPathListRecord, ?>>asList(Keys.FK_SCAN_SCANNED_PATH_LIST_SCANRESULT_1, Keys.FK_SCAN_SCANNED_PATH_LIST_SCANNED_PATH_LIST_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScanScannedPathList as(String alias) {
		return new ScanScannedPathList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ScanScannedPathList rename(String name) {
		return new ScanScannedPathList(name, null);
	}
}
