/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.ScannedPathListRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScannedPathList extends TableImpl<ScannedPathListRecord> {

	private static final long serialVersionUID = 1041677654;

	/**
	 * The reference instance of <code>Scanned_path_list</code>
	 */
	public static final ScannedPathList SCANNED_PATH_LIST = new ScannedPathList();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ScannedPathListRecord> getRecordType() {
		return ScannedPathListRecord.class;
	}

	/**
	 * The column <code>Scanned_path_list.id</code>.
	 */
	public final TableField<ScannedPathListRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Scanned_path_list.file_path</code>.
	 */
	public final TableField<ScannedPathListRecord, String> FILE_PATH = createField("file_path", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>Scanned_path_list</code> table reference
	 */
	public ScannedPathList() {
		this("Scanned_path_list", null);
	}

	/**
	 * Create an aliased <code>Scanned_path_list</code> table reference
	 */
	public ScannedPathList(String alias) {
		this(alias, SCANNED_PATH_LIST);
	}

	private ScannedPathList(String alias, Table<ScannedPathListRecord> aliased) {
		this(alias, aliased, null);
	}

	private ScannedPathList(String alias, Table<ScannedPathListRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ScannedPathListRecord> getPrimaryKey() {
		return Keys.PK_SCANNED_PATH_LIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ScannedPathListRecord>> getKeys() {
		return Arrays.<UniqueKey<ScannedPathListRecord>>asList(Keys.PK_SCANNED_PATH_LIST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ScannedPathList as(String alias) {
		return new ScannedPathList(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ScannedPathList rename(String name) {
		return new ScannedPathList(name, null);
	}
}
