/**
 * This class is generated by jOOQ
 */
package org.home.jooq.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.home.jooq.DefaultSchema;
import org.home.jooq.Keys;
import org.home.jooq.tables.records.SessionScanRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionScan extends TableImpl<SessionScanRecord> {

	private static final long serialVersionUID = -2070855258;

	/**
	 * The reference instance of <code>Session_scan</code>
	 */
	public static final SessionScan SESSION_SCAN = new SessionScan();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SessionScanRecord> getRecordType() {
		return SessionScanRecord.class;
	}

	/**
	 * The column <code>Session_scan.session_name</code>.
	 */
	public final TableField<SessionScanRecord, String> SESSION_NAME = createField("session_name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>Session_scan.scan_id</code>.
	 */
	public final TableField<SessionScanRecord, BigDecimal> SCAN_ID = createField("scan_id", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * Create a <code>Session_scan</code> table reference
	 */
	public SessionScan() {
		this("Session_scan", null);
	}

	/**
	 * Create an aliased <code>Session_scan</code> table reference
	 */
	public SessionScan(String alias) {
		this(alias, SESSION_SCAN);
	}

	private SessionScan(String alias, Table<SessionScanRecord> aliased) {
		this(alias, aliased, null);
	}

	private SessionScan(String alias, Table<SessionScanRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<SessionScanRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<SessionScanRecord, ?>>asList(Keys.FK_SESSION_SCAN_SESSION_1, Keys.FK_SESSION_SCAN_SCANRESULT_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionScan as(String alias) {
		return new SessionScan(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SessionScan rename(String name) {
		return new SessionScan(name, null);
	}
}
